### ISSUE TITLE
Support routing table and subnet binding

### ISSUE THREAD

**Issue by zqfan** [terraform-providers/terraform-provider-tencentcloud#10]
see https://github.com/tencentyun/terraform-provider-tencentcloud/issues/75

**Comment by zqfan** [comment]
Hi, I checked on the tencentcloud terraform provider documentation and don't see anything that allows binding of a subnet to a routing table. Can we add this support? Thanks.
https://www.terraform.io/docs/providers/tencentcloud/r/subnet.html

**Comment by hiscal2015** [comment]
+ 1. Now route_table_id is only supported in Attributes but not Argument.

**Comment by DigitallyBorn** [comment]
This is a pretty big oversight. Please prioritize.

**Comment by Himer** [comment]
has supported.

use the following

```
data "tencentcloud_subnet" "foo" {
	vpc_id = "vpc-8ek64x3d"
	subnet_id = "subnet-d3nsmfwe"
}
```

**Comment by likexian** [comment]
Hello, @hiscal2015 @DigitallyBorn 
This is supported, please try the least version.
Any issue please submit to us.
