### ISSUE TITLE
[Feature request] Add loadbalancer support

### ISSUE THREAD

**Issue by hiscal2015** [terraform-providers/terraform-provider-tencentcloud#11]
Hi, 

Looks like terraform can only bind a loadbalancer for now, can you please add support for CRUD? This is a very important component in a Cloud provider, thanks.

**Comment by hiscal2015** [comment]
looks it is already committed to master branch, when it will be released?

**Comment by lubars** [comment]
This feature is a priority for us as well.

**Comment by likexian** [comment]
Hello @hiscal2015 @lubars 
loadbalancer support has released, docs: https://www.terraform.io/docs/providers/tencentcloud/r/lb.html
If there is any issue, please open to us, thank you.

**Comment by lubars** [comment]
I believe _tencentcloud_lb_ was released in version 1.3.0, but in order to populate _tencentcloud_alb_server_attachment_, it looks like _listener_ and _location_ resources are required.  Do you know when these will be available (assuming there's not an existing means of creating them)?

**Comment by likexian** [comment]
You are right, Currently only support using exists loadbalancer_id listener_id and location_id, we will implement it as soon as possible.

**Comment by likexian** [comment]
refer: https://github.com/terraform-providers/terraform-provider-tencentcloud/issues/37
