### ISSUE TITLE
Supplementary provider documentation

### ISSUE THREAD

**Issue by jijianming** [terraform-providers/terraform-provider-tencentcloud#118]
### Community Note

The parameter **instance_charge_type_prepaid_renew_flag** describes not detailed

### Description
* https://www.terraform.io/docs/providers/tencentcloud/r/instance.html#instance_charge_type_prepaid_renew_flag
The parameter **instance_charge_type_prepaid_renew_flag** has no valid value description.

### New or Affected Resource(s)

* TerraForm 0.12.6

### Potential Terraform Configuration

```hcl
instance_charge_type_prepaid_renew_flag - (Optional) When enabled, the CVM instance will be renew automatically when it reach the end of the prepaid tenancy, Valid values are NOTIFY_AND_AUTO_RENEW, NOTIFY_AND_MANUAL_RENEW,DISABLE_NOTIFY_AND_MANUAL_RENEW NOTE: it only works when instance_charge_type is set to PREPAID,if the parameter is specified as NOTIFY_AND_AUTO_RENEW, if the account balance is sufficient, the instance will be automatically renewed on a monthly basis after the instance expires.
```

### References

* https://www.terraform.io/docs/providers/tencentcloud/r/instance.html#instance_charge_type_prepaid_renew_flag
* https://cloud.tencent.com/document/api/213/15752

**Comment by ausmartway** [comment]
Hi Jijianming,


I have created a PR for this.

https://github.com/terraform-providers/terraform-provider-tencentcloud/pull/117

Regards,

Yulei

**Comment by likexian** [comment]
Thanks to @jijianming and @ausmartway 
The document will update in next release.

**Comment by likexian** [comment]
Hello,
We have refactor the logic of cvm instance, and docs updated.
If there is still some problem, please open a new issue.
