### ISSUE TITLE
documentation for tencentcloud_clb_listener_rule / health_check_httpd_code unclear

### ISSUE THREAD

**Issue by lubars** [terraform-providers/terraform-provider-tencentcloud#133]
The [documentation](https://www.terraform.io/docs/providers/tencentcloud/r/clb_listener_rule.html#health_check_http_code) for _tencentcloud_clb_listener_rule_ attribute _health_check_httpd_code_ is unclear:

> health_check_http_code - (Optional) HTTP Status Code. The default is 31 and value range is 1-31. '0b0001' means the return value '1xx' is health. '0b0010' means the return value '2xx' is health. '0b0100' means the return value '3xx' is health. '0b1000' means the return value '4xx' is health. 0b10000 means the return value '5xx' is health. If you want multiple return codes to indicate health, need to add the corresponding values. NOTES: The 'HTTP' health check of the 'TCP' listener only supports specifying one health check status code. NOTES: Only supports listeners of 'HTTP' and 'HTTPS' protocol.

1. I get errors using "0b0010" or 0b0010; can I just use "2"?  
2. The example at the top of the page, "http_1xx", appears to be invalid:

> Error: Incorrect attribute value type
> 
>   on ../../ICM/etc/Terraform/Tencent/Instance/infrastructure.tf line 500, in resource "tencentcloud_clb_listener_rule" "default":
>  500:   health_check_http_code     = "http_1xx"
> 
> Inappropriate value for attribute "health_check_http_code": a number is
> required.

**Comment by gailwang** [comment]
> The [documentation](https://www.terraform.io/docs/providers/tencentcloud/r/clb_listener_rule.html#health_check_http_code) for _tencentcloud_clb_listener_rule_ attribute _health_check_httpd_code_ is unclear:
> 
> > health_check_http_code - (Optional) HTTP Status Code. The default is 31 and value range is 1-31. '0b0001' means the return value '1xx' is health. '0b0010' means the return value '2xx' is health. '0b0100' means the return value '3xx' is health. '0b1000' means the return value '4xx' is health. 0b10000 means the return value '5xx' is health. If you want multiple return codes to indicate health, need to add the corresponding values. NOTES: The 'HTTP' health check of the 'TCP' listener only supports specifying one health check status code. NOTES: Only supports listeners of 'HTTP' and 'HTTPS' protocol.
> 
> 1. I get errors using "0b0010" or 0b0010; can I just use "2"?
> 2. The example at the top of the page, "http_1xx", appears to be invalid:
> 
> > Error: Incorrect attribute value type
> > on ../../ICM/etc/Terraform/Tencent/Instance/infrastructure.tf line 500, in resource "tencentcloud_clb_listener_rule" "default":
> > 500:   health_check_http_code     = "http_1xx"
> > Inappropriate value for attribute "health_check_http_code": a number is
> > required.

hi lubars, for the first question, using '2' is the right way. '0b0010' is an explanation in the description. The description do cause ambiguity，so it will be modified in the next version 1.18.2. For the second question, the 'http_1xx' is an error in example, it  will be modified in the next version too. Thanks for your comments.

**Comment by likexian** [comment]
Hello @lubars 
This has been fixed in v1.19.0, would you please have a try?
Thank you.

**Comment by likexian** [comment]
Hello,
This issue will be closed, if you have any problems, please open a new issue.
