### ISSUE TITLE
unable to create multiple data disks during instance creation

### ISSUE THREAD

**Issue by lubars** [terraform-providers/terraform-provider-tencentcloud#16]
Because of problems with resource _tencentcloud_cbs_storage_ (see issue #2), I tried instead using an array of data disks, and got the following error:

`* tencentcloud_instance.default: tencentcloud_instance currently only one data disk is supported during instance creation`

In the Tencent console however, I am able to create up to eight data disks during instance creation.

Example:
```
resource "tencentcloud_instance" "default" {
. . .
  data_disks = [
    {
      data_disk_type = "CLOUD_BASIC""
      data_disk_size = "60"
    },
    {
      data_disk_type = "CLOUD_BASIC""
      data_disk_size = "60"
    }
  ]
. . .
}
```

**Comment by zqfan** [comment]
the data disk count limit has been upgrade from 1 to 10 and will be available in next release

**Comment by zqfan** [comment]
fixed by https://github.com/terraform-providers/terraform-provider-tencentcloud/commit/8dfde3436643d74dd13700aa0aaaaad8c8937b2d
