### ISSUE TITLE
HAVIP Support

### ISSUE THREAD

**Issue by LipingMao** [terraform-providers/terraform-provider-tencentcloud#184]
Support HAVIP in Terraform.

**Comment by cedricliu-TX** [comment]
HAVIP is scheduled to be supported at the end of December this year.

**Comment by LipingMao** [comment]
Excited!  @cedricliu-TX

**Comment by oliverpei** [comment]
Hello @LipingMao 
HAVIP has been released on 1.24.0
Docs: https://www.terraform.io/docs/providers/tencentcloud/r/ha_vip.html
If there is any problems, please open a new issue.
