### ISSUE TITLE
VM的数据盘TF中最小为50G，实际最小应该可以是10G

### ISSUE THREAD

**Issue by LipingMao** [terraform-providers/terraform-provider-tencentcloud#185]
TF provider代码中限制了数据盘大小为50G-16000G，但是腾讯官网console中可以创建10G的磁盘，
云硬盘的容量，规格大小如下：
普通云硬盘：10GB - 16000GB
高性能云硬盘：10GB - 16000GB
SSD 云硬盘：100GB - 16000GB
https://cloud.tencent.com/document/product/362/5744

terraform-provider-tencentcloud/tencentcloud/resource_tc_instance.go
                                                "data_disk_size": {
                                                        Type:         schema.TypeInt,
                                                        Required:     true,
                                                        ValidateFunc: validateIntegerInRange(50, 16000),
                                                        Description:  "Size of the system disk. Value range: [50, 16000], and unit is GB.",
                                                },

**Comment by likexian** [comment]
Hello @LipingMao 
This has been fixed and will work in next release.

refer: https://github.com/terraform-providers/terraform-provider-tencentcloud/pull/187

**Comment by LipingMao** [comment]
👍  @likexian

**Comment by LipingMao** [comment]
@likexian  I have verified it works in release v1.23.0 , so OK for me to close this Issue.
