### ISSUE TITLE
image query bug 

### ISSUE THREAD

**Issue by lc273734858** [terraform-providers/terraform-provider-tencentcloud#19]
when I write a image query like this:

data "tencentcloud_image" "my_favorate_image" {
  image_name_regex = "[c|C].*"
}
the result is :
                "data.tencentcloud_image.my_favorate_image": {
                    "type": "tencentcloud_image",
                    "depends_on": [],
                    "primary": {
                        "id": "978916566",
                        "attributes": {
                            "id": "978916566",
                            "image_id": "img-9in0zslb",
                            "image_name_regex": "[c|C].*"
                        },
                        "meta": {},
                        "tainted": false
                    },
                    "deposed": [],
                    "provider": "provider.tencentcloud"
                }

**Comment by zqfan** [comment]
so what is the problem? it seems this data source returns a image correct, what do you expect?

**Comment by lc273734858** [comment]
the regex can't take effect

**Comment by lc273734858** [comment]
image_name_regex = "[c|C]."   can't take effect,
I can't find image.....

**Comment by zqfan** [comment]
what do you mean you can't find an image? data.tencentcloud_image.my_favorate_image.id, img-9in0zslb, is the image matched with your regex.

**Comment by lc273734858** [comment]
there only one image:img-9in0zslb? oh~~

**Comment by zqfan** [comment]
img-9in0zslb is the first image that matches your image_name_regex, which means its name has a c or C in it. this data source seach and return one image, not image list
