### ISSUE TITLE
[Question] Best Practice to use terraform rotate VMs in Tencent Cloud

### ISSUE THREAD

**Issue by LipingMao** [terraform-providers/terraform-provider-tencentcloud#192]
背景：
想要使用Terraform在腾讯云实现虚拟机级别“不可变基础设施”的想法，场景如下：
当需要升级应用时，创建新的VM，部署新的APP，将流量切换到新的VM，确认没有问题后，删除老的VM。

使用Terraform本身可以实现，但是这样就无法享受到腾讯云包月的优惠（删除老的包月VM，就基本按照按需收费了）。腾讯云目前如果不支持类似AWS的RI灵活计费，或者类似阿里云的RI实例券 [1]， 这种情况下使用Terraform频繁增删变更VM就变的非常尴尬，这种情况下仅能使用按需计费。

腾讯云目前是否有什么best practice支持Terraform使用这种case？
 是否有计划支持灵活计费？

[1] https://www.jianshu.com/p/46a5d4b14311

**Comment by woodylic** [comment]
我就此问题咨询过腾讯云，目前的回答是没有。
如果部署频率不是太频繁（例如一个月一次），按需计费打折下来，价格跟包月相差不多，还能接受。但如果部署频率很高（例如开发环境，每个PR触发一次部署），确实存在成本问题。

**Comment by LipingMao** [comment]
@woodylic Thanks for the info.  ;-(

**Comment by likexian** [comment]
@LipingMao @woodylic 
腾讯云有提供RI（Reserved Instance），您可以参考一下以下文档，看看是否可以满足需求。

https://intl.cloud.tencent.com/document/product/213/30571
https://intl.cloud.tencent.com/document/product/213/30572
https://intl.cloud.tencent.com/document/product/213/30573
https://intl.cloud.tencent.com/document/product/213/30619

**Comment by likexian** [comment]
@LipingMao @woodylic 
腾讯云有提供RI（Reserved Instance），您可以参考一下以下文档，看看是否可以满足需求。

https://intl.cloud.tencent.com/document/product/213/30571
https://intl.cloud.tencent.com/document/product/213/30572
https://intl.cloud.tencent.com/document/product/213/30573
https://intl.cloud.tencent.com/document/product/213/30619

**Comment by woodylic** [comment]
@likexian 
我们知道有reserved instance，比如包月。问题在于，@LipingMao 提到的immutable infrastructure实践，每次应用部署实际上是新建CVM并部署应用，同时把原来的CVM杀掉。假设是在dev环境，每天部署一次，按腾讯云的计价方式，相当于一个月内我们购买了30台on-demand CVM，每台使用一天，而不是购买了一台CVM，使用了30天。按这种计价方式，使用immutable infrastructure实践就没法享受包月的优惠了。相较而言，AWS的reserved是按机器数量来计算，而不认某一台VM instance本身，所以AWS下immutable infrastructure并不影响reserved的优惠。

另：你发的链接应该是内网链接？我访问会跳转到腾讯云首页。

**Comment by likexian** [comment]
> @likexian
> 我们知道有reserved instance，比如包月。问题在于，@LipingMao 提到的immutable infrastructure实践，每次应用部署实际上是新建CVM并部署应用，同时把原来的CVM杀掉。假设是在dev环境，每天部署一次，按腾讯云的计价方式，相当于一个月内我们购买了30台on-demand CVM，每台使用一天，而不是购买了一台CVM，使用了30天。按这种计价方式，使用immutable infrastructure实践就没法享受包月的优惠了。相较而言，AWS的reserved是按机器数量来计算，而不认某一台VM instance本身，所以AWS下immutable infrastructure并不影响reserved的优惠。
> 
> 另：你发的链接应该是内网链接？我访问会跳转到腾讯云首页。

1. 可能你误解了，reserved instance类似aws的RI，不等于包月，事实上可以达到按机器数量（使用量）来计算的需求。
2. 贴出的链接是国际版的，请在首页选择一下International，再打开上面的链接。

**Comment by woodylic** [comment]
@likexian thanks, glad to know.

**Comment by likexian** [comment]
> @likexian thanks, glad to know.

不客气，有疑问可以随时咨询我。

**Comment by LipingMao** [comment]
@likexian :   Cool, 国际版本的RI可以满足部分需求， 不过目前我们主要需要使用国内版的。

可能有以下问题：
1）看起来此RI不支持灵活Instance拆分/合并。
2)   国内版是否有计划支持？

多谢

**Comment by likexian** [comment]
> @likexian : Cool, 国际版本的RI可以满足部分需求， 不过目前我们主要需要使用国内版的。
> 
> 可能有以下问题：
> 1）看起来此RI不支持灵活Instance拆分/合并。
> 2) 国内版是否有计划支持？
> 
> 多谢

1. 是的，当前版本没支持拆分/合并，的确不够灵活
2. 国内版暂时还没有计划，建议先使用包年包月

**Comment by LipingMao** [comment]
> > @likexian : Cool, 国际版本的RI可以满足部分需求， 不过目前我们主要需要使用国内版的。
> > 可能有以下问题：
> > 1）看起来此RI不支持灵活Instance拆分/合并。
> > 2) 国内版是否有计划支持？
> > 多谢
> 
> 1. 是的，当前版本没支持拆分/合并，的确不够灵活
> 2. 国内版暂时还没有计划，建议先使用包年包月

Thanks for the info, 期待国内版本支持RI和灵活拆分合并。
