### ISSUE TITLE
TKE cluster_os options inconsistence between terraform and web console

### ISSUE THREAD

**Issue by woodylic** [terraform-providers/terraform-provider-tencentcloud#199]
### Terraform Version

0.12.13

### TencentCloudProvider Version 

1.23

### Affected Resource(s)

tencentcloud_kubernetes_cluster

### Description

In web-console, the OS of TKE cluster already supports Ubuntu 18.04 and CentOS 7.6. According to [source code](https://github.com/terraform-providers/terraform-provider-tencentcloud/blob/master/tencentcloud/extension_tke.go), in terraform it only accepts Ubuntu 16.04 and CentOS 7.2.

**Comment by Himer** [comment]
This product has recently been updated with new support, and terraform has submitted code updates that need to be released in the next release.
#200 
Thanks.

**Comment by likexian** [comment]
Hello @woodylic 
This has been released in 1.24.0, please have a try.
