### ISSUE TITLE
Support instance_charge_type for TKE worker

### ISSUE THREAD

**Issue by woodylic** [terraform-providers/terraform-provider-tencentcloud#203]
Now in both `tencentcloud_kubernetes_cluster` and `tencentcloud_kubernetes_scale_worker`, the worker instance_charge_type is hardcode with `POSTPAID_BY_HOUR`.

Is there any plan to add `instance_charge_type` as configurable option, support both `POSTPAID_BY_HOUR` and `PREPAID`, to keep consistence with web console?

**Comment by likexian** [comment]
Thanks for feedback, we will support it asap.

**Comment by likexian** [comment]
This has been release in 1.24.1, please have a try.
