### ISSUE TITLE
CVM with SPOTPAID return error InvalidInstanceChargeType.OnlySupportedForSpot

### ISSUE THREAD

**Issue by LipingMao** [terraform-providers/terraform-provider-tencentcloud#209]
When I use terraform to boot spot vm, it get the following error, I can use the same size/image to boot in the same az on console:

Error: [TencentCloudSDKError] Code=InvalidInstanceChargeType.OnlySupportedForSpot, Message=The instance charge type SPOTPAID is only supported for spot user., RequestId=9c115e8d-c9c6-4c26-89c2-8197647c5d9e

**Comment by likexian** [comment]
Hello @LipingMao 
Sorry, the spot vm in terraform is not fully implemented, we will fix it soon.

**Comment by likexian** [comment]
Hello @LipingMao
This has been release in v1.25.0, please have a try, thanks.

**Comment by LipingMao** [comment]
@likexian It works for me. Thanks.
