### ISSUE TITLE
Cannot create mongodb instance

### ISSUE THREAD

**Issue by woodylic** [terraform-providers/terraform-provider-tencentcloud#213]
### Terraform Version

0.12.13

### TencentCloud Provider Version

1.24.1

### Affected Resource(s)

* tencentcloud_mongodb_instance

### Terraform Configuration Files

```hcl
resource tencentcloud_mongodb_instance prelive {
  project_id     = 0

  vpc_id         = var.a_valid_vpc_id
  subnet_id      = var.a_valid_subnet_id
  available_zone = "ap-shanghai-3"

  instance_name  = "test"
  machine_type   = "GIO"
  memory         = 4
  volume         = 100
  engine_version = "MONGO_36_WT"
  password       = "mypassword"

  security_groups = [var.a_valid_sg_id]

  tags = {
    env = "test"
  }
}
```

### Panic Output

Error: [TencentCloudSDKError] Code=InvalidParameter, Message=rc check failed[mongodb 商品下单参数校验异常，请联系业务方处理(check params failed, please contact mongodb)][seqId:s0u4921w-qrgt-3y2z-p5kq-kkm3hgita9gi], RequestId=c5b16e66-1380-4c17-81d8-0dbec9448bf5

### Steps to Reproduce

1. `terraform apply`

**Comment by woodylic** [comment]
One related question, why the `password` field is required? Usually terraform code would manage in code repo, but password should be pushed there.

In Web Console it is allowed creating mongodb first, then initialized with a password. This sounds make sense for terraform.

**Comment by woodylic** [comment]
One more, it is hardcode always creating POSTPAID instances, doesn't support PREPAID option.

**Comment by cedricliu-TX** [comment]
> One related question, why the `password` field is required? Usually terraform code would manage in code repo, but password should be pushed there.
> 
> In Web Console it is allowed creating mongodb first, then initialized with a password. This sounds make sense for terraform.

Hi woodylic，the ‘password’ field is required because terraform can Not separate the creating process into creation and initialization, so dose AWS RDS products.

**Comment by cedricliu-TX** [comment]
> One more, it is hardcode always creating POSTPAID instances, doesn't support PREPAID option.

Due to the big differences in charging between POSTPAID instances and PREPAID instances, POSTPAID instances is recognized as the first priority and PREPAID option is scheduled to be supported very soon.

**Comment by oliverpei** [comment]
> ### Panic Output
> Error: [TencentCloudSDKError] Code=InvalidParameter, Message=rc check failed[mongodb 商品下单参数校验异常，请联系业务方处理(check params failed, please contact mongodb)][seqId:s0u4921w-qrgt-3y2z-p5kq-kkm3hgita9gi], RequestId=c5b16e66-1380-4c17-81d8-0dbec9448bf5

Hi @woodylic , sorry for the trouble. We have fixed API bug, please have a try.
You need change machine_type to TGIO, because there is no GIO machine type in ap-shanghai-3. Additional, API error message is not friendly, we will optimize later.

**Comment by likexian** [comment]
Hello @woodylic 
Any questions please open a new issue.
