### ISSUE TITLE
CAM: Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by likexian** [terraform-providers/terraform-provider-tencentcloud#219]
Error: Provider produced inconsistent result after apply

When applying changes to tencentcloud_cam_policy.foo, provider "tencentcloud"
produced an unexpected new value for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

**Comment by gailwang** [comment]
This error is caused by the GetPolicy request and the CreatePolicy request are in a very short time, and the solution is to add time sleep between those actions to fix this issue.
