### ISSUE TITLE
ForceNew not works with region of tencentcloud_ccn_bandwidth_limit

### ISSUE THREAD

**Issue by likexian** [terraform-providers/terraform-provider-tencentcloud#240]
When changes `region` of resource `tencentcloud_ccn_bandwidth_limit`, a new record created but the old one did not destroy.

the below is changing `region` from `ap-guangzhou` to `ap-shanghai`, `ap-guangzhou` still exists.

![1](https://user-images.githubusercontent.com/1175571/70434906-7d82f980-1ac0-11ea-843a-daf48d2db893.png)

**Comment by Himer** [comment]
The bandwidth limit does not support delete operations
The delete operation indicates that the terraform is no longer maintained
