### ISSUE TITLE
vm instance create succeed but terrafrom report failed

### ISSUE THREAD

**Issue by liulangwa** [terraform-providers/terraform-provider-tencentcloud#268]
云主机创建成功，但是terraform报错了，应该是主机就绪时间超过了5分钟，导致了重试失败,应该延长重试时间

```
err = resource.Retry(5*time.Minute, func() *resource.RetryError {
	instance, errRet := cvmService.DescribeInstanceById(ctx, instanceId)
	if errRet != nil {
		return retryError(errRet, "InternalError")
	}
	if instance != nil && *instance.InstanceState == CVM_STATUS_STOPPED {
		return nil
	}
	return resource.RetryableError(fmt.Errorf("cvm instance status is %s, retry...", *instance.InstanceState))
})
if err != nil {
	return err
}
```
![微信图片_20191224173859](https://user-images.githubusercontent.com/25916792/71407077-febbbe00-2674-11ea-89d0-b5923ae0ac11.png)

**Comment by likexian** [comment]
Hello @liulangwa 能不能麻烦你提供一下账户uin或instance id，我们查下是什么原因？

**Comment by liulangwa** [comment]
> Hello @liulangwa 能不能麻烦你提供一下账户uin或instance id，我们查下是什么原因？

100005419791

**Comment by oliverpei** [comment]
重试时间已经延长至15分钟([#271](https://github.com/terraform-providers/terraform-provider-tencentcloud/pull/271))，将在下个版本发布
