### ISSUE TITLE
How can I config the `worker_instances_list` for tke? 

### ISSUE THREAD

**Issue by deancn** [terraform-providers/terraform-provider-tencentcloud#285]
I want to use exist host to create a tke cluster by terraform.  I found the worker_instances_list at  Attributes Reference.

But how can I config the `worker_instances_list`? 

---

* Rerfer: 
[worker_instances_list](https://www.terraform.io/docs/providers/tencentcloud/r/kubernetes_cluster.html#worker_instances_list)

**Comment by Himer** [comment]
Adding an existing instance to the cluster interface was not available until the end of last month, 
and has not yet been added to the terraform

We will arrange for increased support.

3ks

**Comment by likexian** [comment]
Hello @deancn 
this has been released, please have a try.
refer: https://www.terraform.io/docs/providers/tencentcloud/r/kubernetes_cluster_attachment.html

**Comment by deancn** [comment]
@likexian  It works.

One more requirement,  Can we support user-data for `tencentcloud_kubernetes_cluster_attachment`  due to re-install the os.

**Comment by likexian** [comment]
> One more requirement, Can we support user-data for `tencentcloud_kubernetes_cluster_attachment` due to re-install the os.

Got it.
refer: https://github.com/terraform-providers/terraform-provider-tencentcloud/issues/411
