### ISSUE TITLE
data sources:tencentcloud_images   create_time is string

### ISSUE THREAD

**Issue by Himer** [terraform-providers/terraform-provider-tencentcloud#290]
"created_time": {
							Type:        schema.TypeInt,
							Computed:    true,
							Description: "Created time of the image.",
						},

======================

	// 镜像类型
	ImageType *string `json:"ImageType,omitempty" name:"ImageType"`

	// 镜像创建时间
	CreatedTime *string `json:"CreatedTime,omitempty" name:"CreatedTime"`

**Comment by likexian** [comment]
https://github.com/terraform-providers/terraform-provider-tencentcloud/pull/293
