### ISSUE TITLE
Cannot create MongoDB instance because lack of ClusterType

### ISSUE THREAD

**Issue by RonnyChen** [terraform-providers/terraform-provider-tencentcloud#338]
### Terraform Version

Terraform v0.12.19

### Affected Resource(s)

tencentcloud v1.30.1

### Terraform Configuration Files

```hcl
resource "tencentcloud_mongodb_instance" "mongodb" {
  instance_name  = "mongodb"
  memory         = 2
  volume         = 30
  password       = "xxxx"
  engine_version = "MONGO_3_WT"
  machine_type   = "GIO"
  available_zone = "ap-beijing-1"
  vpc_id         = "xxxx"
  subnet_id      = "xxxxx"

}
```

### Debug Output

Error: [TencentCloudSDKError] Code=InvalidParameter, Message=Failed to Check Request params:Field: ClusterType is null, RequestId=80f8fae7-efb1-4b61-97c7-ee2b09058d62

**Comment by oliverpei** [comment]
Hi @RonnyChen , sorry for the trouble. We have fixed API bug, please have a try.
