### ISSUE TITLE
forces replacement after importing an existed cvm instance.

### ISSUE THREAD

**Issue by newhandLiu** [terraform-providers/terraform-provider-tencentcloud#382]
i imported an instance, checked the info in terraform.tfstate as follows.
 

> {
>       "mode": "managed",
>       "type": "tencentcloud_instance",
>       "name": "p4",
>       "provider": "provider.tencentcloud",
>       "instances": [
>         {
>           "schema_version": 0,
>           "attributes": {
>             "allocate_public_ip": null,

  
then when i do terraform plan, it prompt this must be replaced.

> tencentcloud_instance.p4[0] must be replaced
> -/+ resource "tencentcloud_instance" "p4" {
>       + allocate_public_ip                      = false # forces replacement

Terraform v0.12.24
provider.tencentcloud v1.31.0

**Comment by oliverpei** [comment]
Hi @newhandLiu, sorry for the trouble.
Argument `allocate_pubilic_ip` does not support read, it will be set null when `terraform import` is executed, you set it false in main.tf, so inconsistencies lead to replacement.
We will support importing `allocate_pubilic_ip` in provider.tencentcloud v1.31.1 (#384) .

**Comment by likexian** [comment]
Hi @newhandLiu
the fix has been released, please have a try.

**Comment by likexian** [comment]
Hello @newhandLiu 
if you have any problems, please open a new issue.
