### ISSUE TITLE
Allow multiple domain values on `tencentcloud_cdn_domain` creation.

### ISSUE THREAD

**Issue by jianzhiteh** [terraform-providers/terraform-provider-tencentcloud#389]
### Description

Please allow a list of `domain` values to be passed into `tencentcloud_cdn_domain` resource creation.

As checked and verified on the web console of your service, your CDN service does allow creation of CDN resource binding to more than one domain at the same time.

![Jietu20200415-173139](https://user-images.githubusercontent.com/9135584/79322161-03b3be80-7f3f-11ea-87bb-47a8a9265cdc.jpg)

Please make this available also on the terraform resource.

Currently this `domain` arribute only allows `string` type value.

```
Inappropriate value for attribute "domain": string required.
```

### New or Affected Resource(s)

* tencentcloud_cdn_domain

**Comment by oliverpei** [comment]
Each cdn domain is an independently managed resource, each resource manages a domain more clearly in Terraform.
For your problem, you can write the tf file like this
```
variable "domains" {
  default = ["example1.com","example2.com"]
  type = list(string)
}

resource "tencentcloud_cdn_domain" "foo" {
  count = 2
  domain = var.domains[count.index]
  service_type = "web"
  area = "mainland"

  origin {
    origin_type = "ip"
    origin_list = ["127.0.0.1"]
    origin_pull_protocol = "follow"
  }

  https_config {
    https_switch = "off"
    http2_switch = "off"
    ocsp_stapling_switch = "off"
    spdy_switch = "off"
    verify_client = "off"
  }
}
```

**Comment by jianzhiteh** [comment]
Noted with thanks!
