### ISSUE TITLE
Please export CNAME on success `tencentcloud_cdn_domain` creation 

### ISSUE THREAD

**Issue by jianzhiteh** [terraform-providers/terraform-provider-tencentcloud#395]
### Description

Please export the CDN's Domain value to be used with the created resource for CDN. We need to use this exported value to create a CNAME record as part of our workflow on Terraform.

Attached the url for AWS's CloudFront for your reference. (`domain_name` under section "Attribute Reference")

https://www.terraform.io/docs/providers/aws/r/cloudfront_distribution.html#attribute-reference

### Affected Resource(s)

- tencentcloud_cdn_domain

**Comment by likexian** [comment]
Hello @jianzhiteh 
This has been released, please have a try.
