### ISSUE TITLE
Please allow "Filter parameter" (过滤参数) on `tencentcloud_cdn_domain` module

### ISSUE THREAD

**Issue by jianzhiteh** [terraform-providers/terraform-provider-tencentcloud#405]
### Description

From the manual resource creation on the web console, there's one option to Filter Parameter (Ignore Query String). This feature is quite important to our use case.

Please allow this option on the Terraform module too. Thank you!

### New or Affected Resource(s)

* `tencentcloud_cdn_domain`

**Comment by oliverpei** [comment]
Hi @jianzhiteh 
Resource `tencentcloud_cdn_domain` has add argument `full_url_cache` in release v1.33.0, and setting it `false` can ignore query string. 
Please have a try.

**Comment by jianzhiteh** [comment]
It's working, thanks!
