### ISSUE TITLE
redis: TypeId need RedisShardNum and RedisReplicasNum

### ISSUE THREAD

**Issue by likexian** [terraform-providers/terraform-provider-tencentcloud#410]
Error: [TencentCloudSDKError] Code=FailedOperation.SystemError, Message=TypeId need RedisShardNum and RedisReplicasNum, RequestId=a61a937c-c76d-4955-92c5-e8f1faca1020

参数名称 | 必选 | 类型 | 描述
-- | -- | -- | --
RedisShardNum | 否 | Integer | 实例分片数量，Redis2.8主从版、CKV主从版和Redis2.8单机版、Redis4.0主从版不需要填写
RedisReplicasNum | 否 | Integer | 实例副本数量，Redis2.8主从版、CKV主从版和Redis2.8单机版不需要填写
ReplicasReadonly | 否 | Boolean | 是否支持副本只读，Redis2.8主从版、CKV主从版和Redis2.8单机版不需要填写

**Comment by likexian** [comment]
TypeId 也一起补齐吧


参数名称 | 必选 | 类型 | 描述
-- | -- | -- | --
TypeId | 是 | Integer | 实例类型：2 – Redis2.8主从版，3 – Redis3.2主从版(CKV主从版)，4 – Redis3.2集群版(CKV集群版)，5-Redis2.8单机版，6 – Redis4.0主从版，7 – Redis4.0集群版，8 – Redis5.0主从版，9 – Redis5.0集群版

**Comment by Himer** [comment]
#416
