### ISSUE TITLE
Searching 'terraform qcloud' on github but couldn't find this project

### ISSUE THREAD

**Issue by Miss-you** [terraform-providers/terraform-provider-tencentcloud#417]
I searched `terraform qcloud` on github but couldn't find this project, I would like to add a related keyword to make it easier for everyone who want to use the `terraform-provider-tencentcloud`.

![image](https://user-images.githubusercontent.com/3816205/82533623-3ff9c080-9b76-11ea-82ca-3bac19f9d170.png)

**Comment by likexian** [comment]
Hello @Miss-you 
Thanks for your advice.
Now it works: https://github.com/search?q=terraform+qcloud
