### ISSUE TITLE
Tencent Provider is incompatible with current stable Terraform release (0.12.x)

### ISSUE THREAD

**Issue by chanind** [terraform-providers/terraform-provider-tencentcloud#43]
Attempting to use Terraform 0.12.x with this provider results in the following error:

![Screen Shot 2019-06-04 at 09 31 31](https://user-images.githubusercontent.com/200725/58945152-3ae00d80-877b-11e9-8aba-5958ec8a266a.png)

**Comment by nighon** [comment]
I got the same error.

**Comment by lubars** [comment]
We are waiting for 0.12.x support as well.

**Comment by likexian** [comment]
Hello @chanind @nighon @lubars 
We now supported Terraform 0.12.x, please open a new issue if there are any questions.
