### ISSUE TITLE
COS

### ISSUE THREAD

**Issue by lnwu** [terraform-providers/terraform-provider-tencentcloud#437]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
v0.12.24

### Affected Resource(s)

tencentcloud_cos_bucket

### Terraform Configuration Files

```hcl
resource "tencentcloud_cos_bucket" "test-cos" {
  bucket = "test-tf2-1256189307"
  acl    = "public-read-write"
}
```

### Expected Behavior

create resource success.

### Actual Behavior

`Error: cos put bucket error: RequestError: send request failed
caused by: Put http://test-tf2-1256189307.cos.ap-shenzhen.myqcloud.com/: dial tcp: lookup test-tf2-1256189307.cos.ap-shenzhen.myqcloud.com on 192.168.50.1:53: no such host, bucket: test-tf2-1256189307`

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by likexian** [comment]
Hello @lnwu 
The region of ap-shenzhen is invalid, please correct it.
Please refer to: https://intl.cloud.tencent.com/document/product/436/6224
