### ISSUE TITLE
There is an auto replacement when upgrade tencentcloud-terraform SDK from 1.30.0 to higher 

### ISSUE THREAD

**Issue by gailwang** [terraform-providers/terraform-provider-tencentcloud#459]
There is an auto replacement when upgrade tencentcloud-terraform SDK from 1.30.0 to higher version

tencentcloud_mysql_instance.db01 must be replaced
-/+ resource "tencentcloud_mysql_instance" "db01" {
 
      + charge_type       = "POSTPAID" # forces replacement

      + force_delete      = false
    
      - pay_type          = 1 -> null # forces replacement
        period            = 1
     
    }

**Comment by likexian** [comment]
https://github.com/terraform-providers/terraform-provider-tencentcloud/pull/460
