### ISSUE TITLE
need a solution to create instance with private ip

### ISSUE THREAD

**Issue by hiscal2015** [terraform-providers/terraform-provider-tencentcloud#46]
Hi, 

When define a private ip to instance resource, if the instance is being re-creating, the new instance will be created immediately after previous one was destroyed,  it will cause issue because the private IP may need a short time to be released, so there will be error message like "vpc ip is in use", please help to guide a solution or workaround, thanks.

**Comment by likexian** [comment]
Hello @hiscal2015 
This has been fixed, it will work in next release.

**Comment by likexian** [comment]
@hiscal2015 
This has been released, If there are any problems, please open a new issue.

**Comment by hiscal2015** [comment]
@likexian it works now! Thanks for fixing this.
