### ISSUE TITLE
EIP is missing option to enable anycast

### ISSUE THREAD

**Issue by chanind** [terraform-providers/terraform-provider-tencentcloud#49]
Currently only EIPs created in the Tencent Console allow enabling anycast, there's no option in terraform

**Comment by oliverpei** [comment]
Hello @chanind 
Anycast EIP has been released on 1.20.1 (October 08, 2019)
Docs: https://www.terraform.io/docs/providers/tencentcloud/r/eip.html#type
If there is any problems, please open a new issue.
