### ISSUE TITLE
provisioning of data disks is not re-entrant

### ISSUE THREAD

**Issue by lubars** [terraform-providers/terraform-provider-tencentcloud#52]
While attempting to reprovision (due to #18), the following error was seen:

`* tencentcloud_instance.default.1: tencentcloud_instance update on data_disks is not supported yet
`

The only way to get past this error once it's appeared is to destroy and re-apply from scratch.

**Comment by likexian** [comment]
Hello @lubars 
data_disks is not supported to update, you have to recreate the instance.

**Comment by lubars** [comment]
Hi @likexian, thanks for the reply.

I am not actually updating the data disks, simply calling 'apply' multiple times in a row when errors encountered:

1) If 'apply' fails very early, then later 'apply' will create data disks OK
2) If 'apply' succeeds, then later 'apply' is successful too 
3) If 'apply' fails after partial CVM creation, later 'apply' will fail with this error

Maybe what is happening is that, when internal errors are encountered (see other issues filed), only a subset of data disks were created, and Tencent is interpreting the later 'apply' as an attempt to change the number of data disks....

**Comment by likexian** [comment]
Hi @lubars, sorry for the trouble.
I think I don't catch, will you show your tf content and how to reproduce it?
Thank you.
