### ISSUE TITLE
[Feature request] allow security group id as source in security group rules

### ISSUE THREAD

**Issue by hiscal2015** [terraform-providers/terraform-provider-tencentcloud#54]
Please support to add security group id as source in security group rules:

![image](https://user-images.githubusercontent.com/15604715/59995700-aa666000-968a-11e9-9308-9fb7ba4d19fe.png)

![image](https://user-images.githubusercontent.com/15604715/59995664-899e0a80-968a-11e9-89ca-30270bd8c553.png)

**Comment by likexian** [comment]
Hi @hiscal2015 
Please refer to security group resource.
https://www.terraform.io/docs/providers/tencentcloud/r/security_group.html

**Comment by hiscal2015** [comment]
@likexian 
Sorry, which argument can be defined with a security group id as source? cidr_ip?

![image](https://user-images.githubusercontent.com/15604715/59996182-375de900-968c-11e9-9b71-c689fca4d082.png)

**Comment by likexian** [comment]
security group id is returns by resource `tencentcloud_security_group`
https://www.terraform.io/docs/providers/tencentcloud/r/security_group.html

**Comment by hiscal2015** [comment]
@likexian I don't think we're on the same page, I mean, one security group id can be defined as a "source" in one security group rule, just like ip or cidr block, see my picture below:

![image](https://user-images.githubusercontent.com/15604715/59998440-fd8fe100-9691-11e9-8bb9-83b88c8dfa53.png)

**Comment by likexian** [comment]
Yes, you can, so what is the problem?
https://www.terraform.io/docs/providers/tencentcloud/r/security_group_rule.html#security_group_id

**Comment by hiscal2015** [comment]
https://www.terraform.io/docs/providers/tencentcloud/r/security_group_rule.html#security_group_id is used to define the security group id ***you want to add rules to***, not the "来源"

**Comment by hiscal2015** [comment]
To be more clear, from API perspective, it should be one argument under Ingress/egress.N

![image](https://user-images.githubusercontent.com/15604715/59998826-fddcac00-9692-11e9-970b-135661bed4a8.png)

**Comment by likexian** [comment]
Sorry @hiscal2015 
I have catch what your means, we will add support to it soon.

**Comment by hiscal2015** [comment]
> Sorry @hiscal2015
> I have catch what your means, we will add support to it soon.

Wonderful! Thanks a lot.

**Comment by likexian** [comment]
> > Sorry @hiscal2015
> > I have catch what your means, we will add support to it soon.
> 
> Wonderful! Thanks a lot.

Sorry for the trouble.

**Comment by likexian** [comment]
@hiscal2015 
This has been fixed and release, please try the latest version.

The argument name is: source_sgid, please refer to: https://www.terraform.io/docs/providers/tencentcloud/r/security_group_rule.html#source_sgid

Any problem, please open a new issue.
