### ISSUE TITLE
CCN unattachment issue

### ISSUE THREAD

**Issue by hiscal2015** [terraform-providers/terraform-provider-tencentcloud#61]
plugin version: 1.11

Thanks for adding CCN support!

Two issues maybe needed to fix:
1. documents
1.1 missing ""
like 
```
resource tencentcloud_ccn main
```
should be 
```
resource "tencentcloud_ccn" "main"
```

1.2 missing id attribute in tencentcloud_ccn resource (https://www.terraform.io/docs/providers/tencentcloud/r/ccn.html#attributes-reference)

2. ccn unattachement should be "async" action, so a "retry" should be needed to check the status to make sure instances are really unattached, otherwise it will fail when re-creating  tencentcloud_ccn_attachment resources.
```
Error: Error applying plan:

6 error(s) occurred:

* tencentcloud_ccn_attachment.tct_ccn_attach_vpc_eu[2]: 1 error(s) occurred:

* tencentcloud_ccn_attachment.tct_ccn_attach_vpc_eu.2: [TencentCloudSDKError] Code=UnsupportedOperation.CcnAttached, Message=实例 `vpc-9ley7qeh` 已关联云联网。, RequestId=512ab4f8-189f-412d-82df-dad36411b222
* tencentcloud_ccn_attachment.tct_ccn_attach_vpc_cn[0]: 1 error(s) occurred:

* tencentcloud_ccn_attachment.tct_ccn_attach_vpc_cn.0: [TencentCloudSDKError] Code=UnsupportedOperation.CcnAttached, Message=实例 `vpc-oqq3xg74` 已关联云联网。, RequestId=c7c35982-57ec-475b-910b-220e247fb3fc
* tencentcloud_ccn_attachment.tct_ccn_attach_vpc_eu[1]: 1 error(s) occurred:

* tencentcloud_ccn_attachment.tct_ccn_attach_vpc_eu.1: [TencentCloudSDKError] Code=UnsupportedOperation.CcnAttached, Message=实例 `vpc-co7qfpkz` 已关联云联网。, RequestId=84002e68-7cd2-4707-a032-939344263b62
* tencentcloud_ccn_attachment.tct_ccn_attach_vpc_cn[1]: 1 error(s) occurred:

* tencentcloud_ccn_attachment.tct_ccn_attach_vpc_cn.1: [TencentCloudSDKError] Code=UnsupportedOperation.CcnAttached, Message=实例 `vpc-kcei9pl0` 已关联云联网。, RequestId=55d1f3da-dc48-4bc1-a8f6-9b44b6e64237
* tencentcloud_ccn_attachment.tct_ccn_attach_vpc_eu[0]: 1 error(s) occurred:

* tencentcloud_ccn_attachment.tct_ccn_attach_vpc_eu.0: [TencentCloudSDKError] Code=UnsupportedOperation.CcnAttached, Message=实例 `vpc-3sbfh9lx` 已关联云联网。, RequestId=577977fc-b22d-4390-91fe-4c52480eeb18
* tencentcloud_ccn_attachment.tct_ccn_attach_vpc_cn[2]: 1 error(s) occurred:

* tencentcloud_ccn_attachment.tct_ccn_attach_vpc_cn.2: [TencentCloudSDKError] Code=UnsupportedOperation.CcnAttached, Message=实例 `vpc-ebwdztig` 已关联云联网。, RequestId=c9a211a7-7b98-48f8-a382-03fb4b9fa681

```

EDIT:
looks like retry action is already there:
`https://github.com/terraform-providers/terraform-provider-tencentcloud/blob/master/tencentcloud/resource_tc_ccn_attachment.go#L205`
but why it is not working?
You can reproduce this by change the resource name, e.g.
change `resource "tencentcloud_ccn_attachment" "at1"` to `resource "tencentcloud_ccn_attachment" "at2"` and re-run terraform apply.

EDIT2:
by looking at terraform output, looks resource creation and destruction started at the same time because of name changes, so maybe this is not the issue from provider, ignore this please.

**Comment by Himer** [comment]
thanks 

1.we will deal with the document problem in the next version.
2.this attribute["id"] is generally omitted in the document.

Deleting and adding at the same time can cause inexplicable problems, the provider  can't guarantee that.
