### ISSUE TITLE
allocate_public_ip invalid in tencentcloud_instance

### ISSUE THREAD

**Issue by hiscal2015** [terraform-providers/terraform-provider-tencentcloud#62]
provider version: 1.11

no matter `true` or `false` of allocate_public_ip defined in tencentcloud_instance, after instance created, and execute terraform apply again, it will update `allocate_public_ip: "true" => "false"`, and it cannot be updated.

```
  ~ tencentcloud_instance.test
      allocate_public_ip: "true" => "false"
```

```
* tencentcloud_instance.test: 1 error(s) occurred:

* tencentcloud_instance.test: tencentcloud_instance update on allocate_public_ip is not supported yet
```

Additional information: my instance has eip associated after created, I'm not sure if provider detected this as public_ip?

**Comment by likexian** [comment]
Yes, eip is detected as public ip, we now don't support update on allocate_public_ip.

**Comment by zqfan** [comment]
@hiscal2015 
Actually public ip created along with cloud virtual machine is not an EIP, it cannot be detached/unassociated with this instance, hence it is not allowed to be modified, this limit comes from API side.
If you have an EIP associated with the instance after its creation, you are in fact doing a association wihch should be managemented by a resource `tencentcloud_eip_association`.
The probem you are describing, is introduced by https://github.com/terraform-providers/terraform-provider-tencentcloud/pull/42 , which mixes too many codes in different resource, and we cannot catch this problem during code review process. A fix should be done to revert that change (https://github.com/terraform-providers/terraform-provider-tencentcloud/blame/master/tencentcloud/resource_tc_instance.go#L686) or be carefully deal with the logic.
