### ISSUE TITLE
tencentcloud_eip_association should check bind status?

### ISSUE THREAD

**Issue by hiscal2015** [terraform-providers/terraform-provider-tencentcloud#67]
provider version: 1.11
issue:
tencentcloud_eip_association completed successfully but actually eip was not bind to instance.
```
tencentcloud_eip_association.test: Creation complete after 4s (ID: eip-m41t20x6::ins-g1y9urdw)
```
UI:
![eiperror](https://user-images.githubusercontent.com/15604715/61100364-7ff11100-a498-11e9-8a9f-15134a322c77.png)

Should "create" function check bind status after bind request submitted in `https://github.com/terraform-providers/terraform-provider-tencentcloud/blob/master/tencentcloud/resource_tc_eip_association.go#L83-L96`? It should be async action.

**Comment by likexian** [comment]
Hello,
Would you please post your tf config?

**Comment by hiscal2015** [comment]
@likexian it's simple like this:
```
resource "tencentcloud_instance" "test" {
  <whatever>
}

resource "tencentcloud_eip_association" "test" {
  eip_id       = "xxx"
  instance_id  = "${tencentcloud_instance.test.id}"
}
```
We don't fail this all the time, but quite often, most likely there're errors when binding eips to instances, but terraform should not tell users it is ***completed*** in this scenario.

**Comment by likexian** [comment]
Hello, we has add status check after binding request.
