### ISSUE TITLE
cbs should support postpaid type

### ISSUE THREAD

**Issue by zqfan** [terraform-providers/terraform-provider-tencentcloud#8]

**Comment by lubars** [comment]
@zqfan, what error would you expect from trying to create a resource of type _tencentcloud_cbs_storage_ with an account of type "prepaid"?  As I mentioned in issue #2, I've been getting the following error:

`* tencentcloud_cbs_storage.data: json: cannot unmarshal string into Go struct field .code of type int`

And was wondering if prepaid vs. postpaid might be the issue.

**Comment by zqfan** [comment]
post paid only available through API3.0, Terrafrom provider is implemented based on API2.0 (at that time, there is no other choice), we will have to upgrade to API 3.0, then post paid cbs storage resource can be available.

the error info is not caused by prepaid, but inconsistent API 2.0 response, sometimes the code field will be string type then terraform provider fails to parse the response

**Comment by likexian** [comment]
@lubars we have add supported to postpaid cbs.
would you have a try?
if there are any problems, please open a new issue.

**Comment by lubars** [comment]
@likexian, I just tried using most recent release:
```
# terraform version
Terraform v0.12.3
+ provider.null v2.1.2
+ provider.tencentcloud v1.10.0
```
Here is the resource I'm creating:
```
resource "tencentcloud_cbs_storage" "data" {
  storage_name      = "data"
  storage_type      = "CLOUD_BASIC"
  storage_size      = 60
  availability_zone = "na-siliconvalley-1"
}
```
This results in the following error:
> Error: [TencentCloudSDKError] Code=InvalidParameter.DiskConfigNotSupported, Message=you have invalid param value, please check it first: [19021]当前地域不支持当前配置云盘 (beb884b5205c), RequestId=39b6929e-21da-48e8-8643-beb884b5205c
>   on infrastructure.tf line 379, in resource "tencentcloud_cbs_storage" "data":
>  379: resource "tencentcloud_cbs_storage" "data" {

Any idea what I'm doing wrong here?  I got the same error using CLOUD_SSD.

**Comment by likexian** [comment]
@lubars 
CLOUD_BASIC and CLOUD_SSD is sold out, please use CLOUD_PREMIUM instead.

**Comment by likexian** [comment]
@lubars 
Sorry, it seems that there is no stock in na-siliconvalley-1, would you please try na-siliconvalley-2 .

**Comment by lubars** [comment]
@likexian: Getting the same error in _na-siliconvalley-2_:

> Error: [TencentCloudSDKError] Code=InvalidParameter.DiskConfigNotSupported, Message=you have invalid param value, please check it first: [19021]当前地域不支持当前配置云盘 (ce6ad729ae67), RequestId=5b7876a5-7b09-461a-b23f-ce6ad729ae67
> 
>   on ../../ICM/etc/Terraform/Tencent/Instance/infrastructure.tf line 379, in resource "tencentcloud_cbs_storage" "data":
>  379: resource "tencentcloud_cbs_storage" "data" {

**Comment by likexian** [comment]
@lubars
Sorry for the trouble, if there are any problems, please open a new issue.
