### ISSUE TITLE
[Feature request] GAAP support

### ISSUE THREAD

**Issue by 84nm** [terraform-providers/terraform-provider-tencentcloud#81]
Please support GAAP.
https://cloud.tencent.com/product/gaap

I can only configure GAAP on the console, and I feel very inconvenient.
It may be difficult because I can not find the GAAP `tccli` or SDK or API.

**Comment by likexian** [comment]
Hello @84nm 
GAAP has been released on `1.17.0 (September 04, 2019)`
Docs: https://www.terraform.io/docs/providers/tencentcloud/r/gaap_proxy.html
If there is any problems, please open a new issue.
